### PR TITLE
LPO

### PR DESCRIPTION
**Pull request by abhshkdz**
Implements LPO (CVPR 2015): http://vladlen.info/papers/lpo.pdf

### CODE REVIEW

**Comment by aroma123** [comment]
Hi!
1. There is a Proposal.m in both lpo and gop  which is causing error and gop is not working. 
2. Also when I try to generate proposals for lpo, I am getting the following error:
 runObjectProposals('lpo','./demo_img/2007_009084.jpg');
***************Error running calclpoForIm********************
Reference to non-existent field 'params'.

Error in calclpoForIm (line 20)
    if isfield(lpoconfig.params,'model')

Error in runObjectProposals (line 25)
                    	varargout{1} = fh( imageInput, configjson.(char(proposalName)));
Can you please look into these two issues?
Thanks!

**Comment by abhshkdz** [comment]
Hi @aroma123,

1. For which command is it causing an error? `Proposal.m` is never run directly from the root directory. And `example.m` which uses `Proposal.m` can be run by `cd`ing into the respective `matlab` folders: `gop_1.3/matlab` or `lpo/matlab`.
2. That error is because your `config.json` doesn't have the `lpo` parameters. That has to be copied over from [`config.json.example`](https://github.com/abhshkdz/object-proposals/blob/lpo/config.json.example) (have a look right at the bottom for lpo parameters).

Cheers

**Comment by aroma123** [comment]
1. This is the error:
***************Error running calcgopForIm********************
Error using lpo_mex
Setting 'max_iou' not found

Error in Proposal (line 43)
            obj.c_p = lpo_mex( 'newProposal', varargin{:} );

Error in calcgopForIm (line 41)
        p = Proposal('max_iou', max_iou,...

Error in runObjectProposals (line 25)
                    	varargout{1} = fh( imageInput, configjson.(char(proposalName)));

So, calcgopForIm is calling Proposal.m it seems.
2. You are right, it works with the new json file.

**Comment by abhshkdz** [comment]
Hi @aroma123,
 
Yep, you're right. There was a namespace issue between LPO and GOP. I've renamed the functions, and it should be fine now.

**Comment by aroma123** [comment]
Thanks!

**Pull request merged**
